/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registroasistencia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author snake
 */
public class selecionarempleado extends javax.swing.JFrame {
String IDEmpleado1;
String[] nombre = new String [7];

//SACO LA FECHA ACTUAL 
Date date = new Date();
LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
int year  = localDate.getYear();
int month = localDate.getMonthValue();
int day   = localDate.getDayOfMonth();
String fecha = year+"-"+month+"-"+day; //Variable que tiene la fecha actual

    public selecionarempleado(String IDEmpleado) {
        IDEmpleado1=IDEmpleado;
        initComponents();
        String[] nombres = new String [7];
        int contador=0;
        try {                                     
            String usuario = "root"; //nombre del usuario
            String clave= ""; //la clave, por lo general es en vacio
            String url = "jdbc:mysql://localhost:3306/registroasistencia"; //donde se encuentra la base de datos
            Connection con; //importar sql.connection para la conexion
            Statement stmt; //importar sql statemenr
            ResultSet rs; //resultado de las consultas
            ResultSet rs2;
            Statement stmt2;
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //hacer la conexion con la base de datos
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RegistroAsistencia.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            con = DriverManager.getConnection(url,usuario,clave); //montar el servidor
            
            //IMPRIMIR LOS NOMRBES DE LOS EMPLEADOS EN LA INTERFAZ DE LOS BOTONES
            stmt = con.createStatement(); //inicializar stmt
            rs = stmt.executeQuery("SELECT * FROM Empleado");
            rs.next();
            do{
                if(contador<6)
                {
                    nombres[contador] = rs.getString("Nombre") + " ";
                    nombre[contador] = rs.getString("Nombre");
                    nombres[contador] = nombres[contador]+rs.getString("Apaterno");
                    contador++;
                }
            }while(rs.next());            
            /*for(int x = 0; x<7; x++)
            {
                System.out.println(nombres[x]);
            }*/
            empleado1.setText("");
            empleado1.setText(nombres[0]);
            empleado2.setText("");
            empleado2.setText(nombres[1]);
            empleado3.setText("");
            empleado3.setText(nombres[2]);
            empleado4.setText("");
            empleado4.setText(nombres[3]);
            empleado5.setText("");
            empleado5.setText(nombres[4]);
            empleado6.setText("");
            empleado6.setText(nombres[5]);
            
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        empleado1 = new javax.swing.JButton();
        empleado2 = new javax.swing.JButton();
        empleado3 = new javax.swing.JButton();
        empleado4 = new javax.swing.JButton();
        empleado5 = new javax.swing.JButton();
        empleado6 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Empleados de la tienda");

        empleado1.setText("jButton1");
        empleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado1ActionPerformed(evt);
            }
        });

        empleado2.setText("jButton2");
        empleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado2ActionPerformed(evt);
            }
        });

        empleado3.setText("jButton3");
        empleado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado3ActionPerformed(evt);
            }
        });

        empleado4.setText("jButton4");
        empleado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado4ActionPerformed(evt);
            }
        });

        empleado5.setText("jButton5");
        empleado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado5ActionPerformed(evt);
            }
        });

        empleado6.setText("jButton6");
        empleado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado6ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Regresar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empleado3)
                    .addComponent(empleado2)
                    .addComponent(empleado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleado4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empleado5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(empleado6)
                        .addGap(160, 160, 160))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(360, 360, 360))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(396, 396, 396))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(empleado1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(empleado4)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado2)
                    .addComponent(empleado5))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado3)
                    .addComponent(empleado6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false);
        informacionempleado info = new informacionempleado(IDEmpleado1);
        info.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void empleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado1ActionPerformed
        int bandera = 0;
        metodos metodo = new metodos();
        this.setVisible(false);
        menuactividades menu = new menuactividades(IDEmpleado1,metodo.buscar_id(nombre[0]),nombre[0]);
        menu.setVisible(true);
    }//GEN-LAST:event_empleado1ActionPerformed

    private void empleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado2ActionPerformed
        int bandera = 0;
        metodos metodo = new metodos();
        this.setVisible(false);
        menuactividades menu = new menuactividades(IDEmpleado1,metodo.buscar_id(nombre[1]),nombre[1]);
        menu.setVisible(true);
    }//GEN-LAST:event_empleado2ActionPerformed

    private void empleado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado3ActionPerformed
        int bandera = 0;
        metodos metodo = new metodos();
        this.setVisible(false);
        menuactividades menu = new menuactividades(IDEmpleado1,metodo.buscar_id(nombre[2]),nombre[2]);
        menu.setVisible(true);
    }//GEN-LAST:event_empleado3ActionPerformed

    private void empleado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado4ActionPerformed
        int bandera = 0;
        metodos metodo = new metodos();
        this.setVisible(false);
        menuactividades menu = new menuactividades(IDEmpleado1,metodo.buscar_id(nombre[3]),nombre[3]);
        menu.setVisible(true);
    }//GEN-LAST:event_empleado4ActionPerformed

    private void empleado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado5ActionPerformed
        int bandera = 0;
        metodos metodo = new metodos();
        this.setVisible(false);
        menuactividades menu = new menuactividades(IDEmpleado1,metodo.buscar_id(nombre[4]),nombre[4]);
        menu.setVisible(true);
    }//GEN-LAST:event_empleado5ActionPerformed

    private void empleado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado6ActionPerformed
        int bandera = 0;
        metodos metodo = new metodos();
        this.setVisible(false);
        menuactividades menu = new menuactividades(IDEmpleado1,metodo.buscar_id(nombre[5]),nombre[5]);
        menu.setVisible(true);
    }//GEN-LAST:event_empleado6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selecionarempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selecionarempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selecionarempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selecionarempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empleado1;
    private javax.swing.JButton empleado2;
    private javax.swing.JButton empleado3;
    private javax.swing.JButton empleado4;
    private javax.swing.JButton empleado5;
    private javax.swing.JButton empleado6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
